//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoActPlugin.Updater {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateQuestionForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateQuestionForm() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeoActPlugin.Updater.UpdateQuestionForm", typeof(UpdateQuestionForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill 的類型 System.Windows.Forms.DockStyle 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.DockStyle btnConfirm_Dock {
            get {
                object obj = ResourceManager.GetObject("btnConfirm.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=3,Y=3} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point btnConfirm_Location {
            get {
                object obj = ResourceManager.GetObject("btnConfirm.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=334, Height=29} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size btnConfirm_Size {
            get {
                object obj = ResourceManager.GetObject("btnConfirm.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int btnConfirm_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnConfirm.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 安裝 的當地語系化字串。
        /// </summary>
        internal static string btnConfirm_Text {
            get {
                return ResourceManager.GetString("btnConfirm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill 的類型 System.Windows.Forms.DockStyle 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.DockStyle btnDeny_Dock {
            get {
                object obj = ResourceManager.GetObject("btnDeny.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=343,Y=3} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point btnDeny_Location {
            get {
                object obj = ResourceManager.GetObject("btnDeny.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=334, Height=29} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size btnDeny_Size {
            get {
                object obj = ResourceManager.GetObject("btnDeny.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 1 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int btnDeny_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnDeny.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        internal static string btnDeny_Text {
            get {
                return ResourceManager.GetString("btnDeny.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill 的類型 System.Windows.Forms.DockStyle 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.DockStyle label1_Dock {
            get {
                object obj = ResourceManager.GetObject("label1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=3,Y=0} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=680, Height=28} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 是否現在更新至新版本 {0}  的當地語系化字串。
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MiddleCenter 的類型 System.Drawing.ContentAlignment 當地語系化資源。
        /// </summary>
        internal static System.Drawing.ContentAlignment label1_TextAlign {
            get {
                object obj = ResourceManager.GetObject("label1.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 1 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int tableLayoutPanel1_ColumnCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.ColumnCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill 的類型 System.Windows.Forms.DockStyle 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.DockStyle tableLayoutPanel1_Dock {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Windows.Forms.TableLayoutSettings 的當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.TableLayoutSettings tableLayoutPanel1_LayoutSettings {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.LayoutSettings", resourceCulture);
                return ((System.Windows.Forms.TableLayoutSettings)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=0,Y=0} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point tableLayoutPanel1_Location {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 4 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int tableLayoutPanel1_RowCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.RowCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=686, Height=476} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size tableLayoutPanel1_Size {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int tableLayoutPanel1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 2 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int tableLayoutPanel2_ColumnCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.ColumnCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill 的類型 System.Windows.Forms.DockStyle 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.DockStyle tableLayoutPanel2_Dock {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Windows.Forms.TableLayoutSettings 的當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.TableLayoutSettings tableLayoutPanel2_LayoutSettings {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.LayoutSettings", resourceCulture);
                return ((System.Windows.Forms.TableLayoutSettings)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=3,Y=428} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point tableLayoutPanel2_Location {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 1 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int tableLayoutPanel2_RowCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.RowCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=680, Height=35} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size tableLayoutPanel2_Size {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 2 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int tableLayoutPanel2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill 的類型 System.Windows.Forms.DockStyle 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.DockStyle webBrowser1_Dock {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=3,Y=31} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point webBrowser1_Location {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=20, Height=18} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size webBrowser1_MinimumSize {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.MinimumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=680, Height=391} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size webBrowser1_Size {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 1 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int webBrowser1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
